accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    
    path('login',views.login_view,name='login'),
    #path('logout',views.logout_view,name='logout'),
    path('signup',views.signup_view,name='signup'),
    # Login
    # Logout
    # Registration /signup
]

blog/urls.py
from django.urls import path
from blog.views import *

app_name = 'blog'

urlpatterns = [
    
    path('', blog_view, name= 'index'),
    path('post-<int:pid>', blog_single, name= 'single'),
    path('category/<str:cat_name>', blog_view, name= 'category'),
    path('tag/<str:tag_name>', blog_view, name= 'tag'),
    path('author/<str:author_username>', blog_view, name= 'author'),
    path('search/',blog_search, name= 'search'),
    path('test', test, name='test'),
]

mysiteProject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from mysiteApp.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
from debug_toolbar.toolbar import debug_toolbar_urls



sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mysiteApp.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    
    path('sitemap.xml', sitemap,{'sitemaps':sitemaps}, 
         name='django.contrib.sitemaps.views.sitemap'),
    re_path('robots.txt', include('robots.urls')),
    path('captcha/', include('captcha.urls')),
] + debug_toolbar_urls()

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
# Create your views here.
def login_view(request):
    """
    if request.user.is_authenticated:
        msg= f'user is authenticated as {request.user.username}'
    else:
        msg='uesr is not authenticated'
    """
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request,username=username,password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
            
    return render(request,'accounts/login.html')#,{'msg':msg})

#def logout_view(request):
    #return render(request,'accounts/logout.html')

def signup_view(request):
    return render(request,'accounts/signup.html')
    

templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="icon" type="image/png" href="{% static 'img/login/favicon.ico' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
</head>
<body>

	<div class="limiter">
		<div class="container-login100" method="post" action={% url 'accounts:login' %}>
            {% csrf_token %}
			<div class="wrap-login100">
				<form class="login100-form validate-form p-l-55 p-r-55 p-t-178" method="post">
					{% csrf_token %}
					<span class="login100-form-title">
						Sign In
					</span>

					<div class="wrap-input100 validate-input m-b-16">
						<input class="input100" type="text" name="username" placeholder="Username">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input">
						<input class="input100" type="password" name="password" placeholder="Password">
						<span class="focus-input100"></span>
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn" type="submit">
							Sign in
						</button>
					</div>
				</form>
			</div>
		</div>
	</div>

	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
	<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
	<script src="{% static 'js/login.js' %}"></script>
</body>
</html>